#/// \dir
#/// Contains a minimal set of files for adding new tests to SpEC

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What subdirectories should also be compiled (one for each test)
SUBDIRECTORIES =

LINKED_LIBS = DataMesh MyContainers ErrorHandling LowLevelUtils

EXECUTABLES = MyMeshExec MyDM_Exec MyTDM_Exec2

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

