#/// \dir
#/// Contains a minimal set of files for adding a new executable to SpEC

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What libraries does this executable depend on
FACTORY_LIBS = Example01jwendell \
	StringParsing \
	MiscUtils \
	MyContainers \
	ErrorHandling \
	LowLevelUtils

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = MultAddInput

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

