#/// \dir
#/// Contains tests for wthrowe's assignment 02

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What subdirectories should also be compiled (one for each test)
SUBDIRECTORIES =

# What libraries does this executable depend on
LINKED_LIBS = Assignment02wthrowe StringParsing MyContainers \
  ErrorHandling LowLevelUtils

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = TestAssignment02wthrowe

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules
