#/// \dir
#/// Template for a user's personal directory for the 2011 SpEC Class.

# Where is SPEC_HOME relative to this dir
CODE_HOME = ../../..

SUBDIRECTORIES = TemplateSubdir Example01Brett Assignment01Brett \
	Assignment02Brett

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

