#/// \dir
#/// Contains a minimal set of files for adding a new subdirectory to SpEC,
#/// including executables and tests.

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../..

# What subdirectories should also be compiled
SUBDIRECTORIES = Executables Tests

# What .cpp files should be compiled (replace .cpp with .o)
OBJECT_FILES_INTO_LIB = MyFirstLibCasey.o

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

