#/// \dir
#/// Contains wthrowe's Assignment 03

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../..

# What subdirectories should also be compiled
SUBDIRECTORIES = Executables

# What .cpp files should be compiled (replace .cpp with .o)
OBJECT_FILES_INTO_LIB = TensorInversewthrowe.o

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

