#/// \dir
#/// Contains a minimal set of files for adding a new executable to SpEC

CODE_HOME = ../../../../..

LINKED_LIBS = Assignment05fhebert StringParsing IO MiscUtils \
  ErrorHandling MyContainers MpiWrappers LowLevelUtils Assignment05fhebert

EXECUTABLES = Problem2Exec

##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

