#/// \dir
#/// Contains a minimal set of files for adding new tests to SpEC

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What subdirectories should also be compiled
SUBDIRECTORIES = 

# What subdirectories should also be compiled (one for each test)
INCLUDED_AND_LINKED_LIBS = Assignment02Iryna StringParsing MyContainers \
ErrorHandling LowLevelUtils

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = TestAssignment02Iryna

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

