#/// \dir
#/// Contains the MultiplyAdd executable

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What libraries does this executable depend on
LINKED_LIBS = Assignment01wthrowe StringParsing LowLevelUtils \
  MyContainers ErrorHandling

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = MultiplyAdd

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

