#/// \dir
#/// Contains executables for Assignment 05

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What libraries does this executable depend on
LINKED_LIBS = Assignment05wthrowe StringParsing IO MiscUtils \
  ErrorHandling MyContainers MpiWrappers LowLevelUtils

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = Problem2Exec

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

