#/// \dir
#/// Contains tests for Assignment 04

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What subdirectories should also be compiled (one for each test)
SUBDIRECTORIES = TestVolume

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

