#/// \dir
#/// wthrowe's personal directory for the 2011 SpEC Class.

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../..

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

