#/// \dir
#/// Contains a minimal set of files for adding a new executable to SpEC

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../../..

# What libraries does this executable depend on
LINKED_LIBS = Assignment03Aaron Tensor DataMesh MyContainers ErrorHandling LowLevelUtils

# What .cpp files containing a main function should be compiled (remove .cpp)
EXECUTABLES = MyMeshExec MyMeshExec2 MyDM_Exec MyDM_Exec2 MyTensorStructureExec MyTensorExec MyTDM_Exec MyTDM_Exec2 MyMatrixExec

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

