#/// \dir
#/// Contains wthrowe's solution to assignment 02

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../..

# What subdirectories should also be compiled
SUBDIRECTORIES = Tests

# What .cpp files should be compiled (replace .cpp with .o)
OBJECT_FILES_INTO_LIB = Assignment02wthrowe.o

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

